### ISSUE TITLE
Story admin classrom list

### ISSUE THREAD

**Issue by vuknovakovic** [riskmatf/turing#12]
+ [x] List of classroom grouped by location
+ [x] Make location group collapsable
+ [x] Always keep same order of classrooms possible sort
+ [x] Computer count show real state of computers maybe make it number of working computer number of broken number of ones with warning or something like that
+ [x] "Remove button" next to classroom
+ [x] Add button currently via svg

**Comment by basilisk6** [comment]
Done, made issues for binding corresponding buttons
