### ISSUE TITLE
Application skelet

### ISSUE THREAD

**Issue by vuknovakovic** [riskmatf/turing#19]
+ [x] Create component for basic layout
+ [x] Routes and basic components for
    + [x] / (home)
    + [x] /classrooms (classroomList)
    + [x] /classrooms/:id (classroomView)
    + [x] /classrooms/:id/:compId (computerView)
    + [x] /classrooms/:id/:compId/:reportId (reportView, reportAdd)
    + [x] /tutorial 
    + [x] * (404 and stuff)

**Comment by atfoc** [comment]
+ [x] Setup plugin for request
