### ISSUE TITLE
Create route /classrooms/classroomId

### ISSUE THREAD

**Issue by atfoc** [riskmatf/turing#32]
Having a list of classrooms as a resource in our API I think it only makes sense to have a single classroom as well. 
+ [ ] Remove schema_url from classroomList resource
+ [ ] Return classroom on this route with data
```typescript
interface Classroom {
name: String,
location: String,
schemaUrl: String,
computer: Array<Computers>
}
```
Note: keep computers as is

**Comment by vuknovakovic** [comment]
Closing as this will not do us any good.
