### ISSUE TITLE
Story admin layout

### ISSUE THREAD

**Issue by vuknovakovic** [riskmatf/turing#9]
+ [x] Main admin layout should have
    + [x] Nav to reports
    + [x]  Classroom list
    + [x] Add new Admin
    + [x] Account Page
    + [x] Should show reports by default
    + [x] Add logout button

**Comment by atfoc** [comment]
This is  baseLayout for admin

**Comment by basilisk6** [comment]
Main admin layout done.
Opened issue for binding logout button
